### ISSUE TITLE
Feedbacks from morning section

### ISSUE THREAD

**Issue by Dandush03** [sipe-daniel/positioning-and-floating-elements#3]
## here are some of the things you should consider before continuing:

- [x] make sure each one of your classes would have a space between them, otherwise, it will give you some Sticklers error for example:

`clas1 {`
`  display:none;`
`}`
` `
`clas2 {`
`  display:block;`
`}`
` `

- [x] Don't forget to add an h2-h6 header to each section you have.

- [x] and most importantly, don't forget that you are supposed to use the only float to align your elements in this project. make sure you're not using any grid, inline nor flex containers.

## feel always free to write to me, I'll get back to you as soon as I can.

# Happy Coding! :+1:

**Comment by maosan132** [comment]
Thank you for the comments!
